// <auto-generated />
using System;
using EntityFrameworkCore.MySQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DownTrack.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241208051639_CreateEvaluacionAndRelationships2")]
    partial class CreateEvaluacionAndRelationships2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.BajaEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CausaBaja")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaBaja")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("BajasEquipos");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SeccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeccionId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaAdq")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ubicacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("JefeSeccId")
                        .HasColumnType("int");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("int");

                    b.Property<string>("Valoracion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("JefeSeccId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.MantenimientoRealizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("CostoMant")
                        .HasColumnType("double");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("date");

                    b.Property<int?>("MantenimientoId")
                        .HasColumnType("int");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("MantenimientoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("MantenimientosRealizados");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Seccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("JefeSeccId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("JefeSeccId");

                    b.ToTable("Secciones");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AñosExp")
                        .HasColumnType("int");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Salario")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.BajaEquipo", b =>
                {
                    b.HasOne("EntityFrameworkCore.MySQL.Models.Equipo", "Equipo")
                        .WithMany("Bajas")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntityFrameworkCore.MySQL.Models.Tecnico", "Tecnico")
                        .WithMany("BajasRealizadas")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipo");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Departamento", b =>
                {
                    b.HasOne("EntityFrameworkCore.MySQL.Models.Seccion", "Seccion")
                        .WithMany("Departamentos")
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Evaluacion", b =>
                {
                    b.HasOne("EntityFrameworkCore.MySQL.Models.Usuario", "JefeSecc")
                        .WithMany("EvaluacionesOtorgadas")
                        .HasForeignKey("JefeSeccId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EntityFrameworkCore.MySQL.Models.Tecnico", "Tecnico")
                        .WithMany("EvaluacionesRecibidas")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("JefeSecc");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.MantenimientoRealizado", b =>
                {
                    b.HasOne("EntityFrameworkCore.MySQL.Models.Equipo", "Equipo")
                        .WithMany("MantenimientosRealizados")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntityFrameworkCore.MySQL.Models.Mantenimiento", "Mantenimiento")
                        .WithMany("MantenimientosRealizados")
                        .HasForeignKey("MantenimientoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntityFrameworkCore.MySQL.Models.Tecnico", "Tecnico")
                        .WithMany("MantenimientosRealizados")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipo");

                    b.Navigation("Mantenimiento");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Seccion", b =>
                {
                    b.HasOne("EntityFrameworkCore.MySQL.Models.Usuario", "JefeSecc")
                        .WithMany("Secciones")
                        .HasForeignKey("JefeSeccId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JefeSecc");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Equipo", b =>
                {
                    b.Navigation("Bajas");

                    b.Navigation("MantenimientosRealizados");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Mantenimiento", b =>
                {
                    b.Navigation("MantenimientosRealizados");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Seccion", b =>
                {
                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Tecnico", b =>
                {
                    b.Navigation("BajasRealizadas");

                    b.Navigation("EvaluacionesRecibidas");

                    b.Navigation("MantenimientosRealizados");
                });

            modelBuilder.Entity("EntityFrameworkCore.MySQL.Models.Usuario", b =>
                {
                    b.Navigation("EvaluacionesOtorgadas");

                    b.Navigation("Secciones");
                });
#pragma warning restore 612, 618
        }
    }
}
